feat: refactor
eggjs/egg-view-xtpl pull request #2
Opened 2017-03-13 08:51 UTC by ngot

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-03-13 08:56 UTC, ngot commented
重构了一版

@popomore @atian25 看下
 loadpath 本来的版本就没有效果的，根本走不到那个逻辑。

2017-03-13 09:13 UTC, popomore commented on test/fixtures/apps/xtpl-demo/app/controller/string.js
> +    viewEngine: 'xtpl',
第三个参数

2017-03-13 09:17 UTC, popomore commented on lib/xtpl.js
> +const fs = require('fs-then');
用 mz 吧

2017-03-13 09:21 UTC, atian25 requested changes

2017-03-13 09:21 UTC, atian25 commented on app/extend/application.js
> +const ENGINE = require('../../lib/engine');
这个不是静态变量，不用全大写吧？

`const engine = require('../../lib/engine');`

2017-03-13 09:21 UTC, atian25 commented on app/extend/application.js
> +const XTPL = Symbol('app#XTPL');
这个用 `const ENGINE = Symbol('app#xtpl')` 感觉合适点

2017-03-13 09:21 UTC, atian25 commented on app/extend/application.js
> +   * @member {XTPLEnvironment} Application#xtpl
`XTPLEnvironment` 这个是 xtpl 那边的 class name 拼写么?

2017-03-13 09:21 UTC, atian25 commented on lib/xtpl.js
> +const INSTANCECACHESYMBOL = Symbol('XTPL#INSTANCECACHE');
这几个全大写看起来好累.. SYMBOL 后缀没必要加了吧

`const INSTANCE_CACHE = Symbol('XtplEngine#instanceCache');`

下面几个类似

2017-03-13 09:21 UTC, atian25 commented on lib/xtpl.js
> +  readFile(pathname, config) {
perfer `pathName` or `fileName`

2017-03-13 09:21 UTC, atian25 commented on lib/xtpl.js
> +      const instance = this.getInstance({
xtpl 实际业务中会有很多 instance?

2017-03-13 09:21 UTC, atian25 commented on lib/xtpl.js
> +    function load(tpl, callback) {
这函数能否变为私有成员函数? 不用每次都 new ?

2017-03-13 09:21 UTC, atian25 commented on package.json
> +    "fs-then": "^0.2.0",
用 `mz` ? https://www.npmjs.com/package/mz

2017-03-13 09:21 UTC, atian25 commented on test/fixtures/apps/xtpl-demo/app/view/gbk.xtpl
> +< ��� {{ name  }}
`���`

2017-03-13 09:21 UTC, atian25 commented on test/fixtures/apps/xtpl-cache/app/controller/fileCache.js
> +  this.app.xtpl.fnCache.reset();
要支持个 `cleanCache()` 么?

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +    if (cache && (cached = self.instanceCache.peek(pathname))) {
为啥用 self？

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +  get fileCache() {
这几个为啥不再构造函数里面

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +    copy(this.defaultOptions).to(options);
非递归的用 Object.assign 就好了？

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +      fn.render(data, { commands: options.commands }, renderTpl);
这个会有异常么

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +          return new Promise((resolve, reject) => {
嵌套这么深还是用 generator 吧

2017-03-13 09:42 UTC, popomore commented on lib/xtpl.js
> +      if (cache && self.fnCache.has(pathname)) {
readFile 里有一层缓存了

2017-03-13 09:46 UTC, ngot commented on lib/xtpl.js
> +    copy(this.defaultOptions).to(options);
这里默认值，复制利用 copy比较方便一些

2017-03-13 09:47 UTC, ngot commented on lib/xtpl.js
> +      fn.render(data, { commands: options.commands }, renderTpl);
会有的，比如语法错误，传入的扩展 commands 抛异常

2017-03-13 10:24 UTC, ngot commented on lib/xtpl.js
> +    if (cache && (cached = self.instanceCache.peek(pathname))) {
跟着其他几处，顺手写的，我改掉吧

2017-03-13 10:36 UTC, ngot commented on lib/xtpl.js
> +      const instance = this.getInstance({
一个request 一个 instance

2017-03-13 14:08 UTC, popomore commented on lib/xtpl.js
> +    copy(this.defaultOptions).to(options);
和 Object.assign 一个意思吧？

2017-03-13 14:08 UTC, popomore commented on lib/xtpl.js
> +      fn.render(data, { commands: options.commands }, renderTpl);
那要 try/catch

2017-03-13 14:09 UTC, popomore commented on lib/xtpl.js
> +const INSTANCECACHESYMBOL = Symbol.for('XTPL#INSTANCECACHE');
为啥用 Symbol.for

2017-03-13 14:10 UTC, popomore commented on lib/xtpl.js
> +    this[INSTANCECACHESYMBOL] = new LRU();
有个疑问，模板为什么要用 lru

2017-03-13 14:11 UTC, popomore commented on lib/xtpl.js
> +      fn.render(data, { commands: options.commands }, renderTpl);
按上面说的，改成 generator 吧

2017-03-14 03:08 UTC, ngot commented on app/extend/application.js
> +const ENGINE = require('../../lib/engine');
我改成 
```js
const XTPLSYMBOL = Symbol('app#xtpl');
const engine = require('../../lib/engine');
```
吧

2017-03-14 03:08 UTC, ngot commented on app/extend/application.js
> +   * @member {XTPLEnvironment} Application#xtpl
这个不是，xtpl没有这个概念。我改成自定义的 xtpl 吧

2017-03-14 03:09 UTC, ngot commented on test/fixtures/apps/xtpl-demo/app/view/gbk.xtpl
> +< ��� {{ name  }}
这个是 gbk

2017-03-14 03:10 UTC, ngot commented on test/fixtures/apps/xtpl-cache/app/controller/fileCache.js
> +  this.app.xtpl.fnCache.reset();
暂时，貌似还没有什么用。以后支持吧

2017-03-14 03:12 UTC, ngot commented on lib/xtpl.js
> +    this[INSTANCECACHESYMBOL] = new LRU();
如果按照现在这种使用方式，用 map也就够了。不过，lru的话，可以比较方便后续扩展设置缓存超时时间，实际使用上也没什么副作用。比较方便。

2017-03-14 03:22 UTC, ngot commented on lib/xtpl.js
> +const INSTANCECACHESYMBOL = Symbol.for('XTPL#INSTANCECACHE');
考虑给这个测试用的 https://github.com/eggjs/egg-view-xtpl/blob/b59e7d8224336d79333c7a1cff98a3e6e7cd7ee0/test/fixtures/apps/xtpl-cache/app/controller/fileCache.js#L10

fncache和filecache确实有些重复了。我把filecache去掉吧，只缓存编译后的结果。这个测试就不要了。

2017-03-14 03:36 UTC, popomore commented on lib/xtpl.js
> +    this[INSTANCECACHESYMBOL] = new LRU();
只是疑问为什么需要缓存超时，模板除非是文件变更，不太会变化的。

2017-03-14 04:21 UTC, ngot commented on lib/xtpl.js
> +    copy(this.defaultOptions).to(options);
等价与 Object.assign({}, defaultOptions, options);

2017-03-14 04:27 UTC, ngot commented on lib/xtpl.js
> +    this[INSTANCECACHESYMBOL] = new LRU();
目前设置默认配置是不超时的，也没开放设置的

2017-03-14 04:28 UTC, ngot commented
改了，大家再看看 @atian25 @popomore

2017-03-14 05:38 UTC, atian25 approved these changes

2017-03-14 05:38 UTC, atian25 commented on app/extend/application.js
> +const XTPLSYMBOL = Symbol('app#xtpl');
`XTPL` 就好了吧，不用加 SYMBOL

2017-03-14 05:38 UTC, atian25 commented on lib/view.js
> +    debug('filename:', filename);
`debug('render filename:'`

2017-03-14 05:38 UTC, atian25 commented on lib/view.js
>      const config = Object.assign({}, this.config, viewOptions, { cache: null });
ejs 那边加 `cache: null` 是因为 renderString 无法缓存，不这么做会报错， xtpl 这边也需要？

2017-03-14 05:38 UTC, atian25 commented on package.json
>      "egg-plugin"
加一个 `egg-view`

2017-03-14 05:42 UTC, ngot commented on lib/view.js
>      const config = Object.assign({}, this.config, viewOptions, { cache: null });
这个是没用的

2017-03-14 05:47 UTC, atian25 reviewed
其他 +1。 @popomore 再看看。


PS: 话说， xtpl 怎么设计得每一个 request 一个 instance，浪费啊。

2017-03-14 05:47 UTC, atian25 commented on lib/view.js
> +    debug('render filename::', filename);
多了一个 `:`

2017-03-14 05:48 UTC, atian25 commented
windows 用例挂了

2017-03-14 06:31 UTC, ngot commented
@atian25 xtemplate自己在windows下，挂了...我提个issue吧，不影响插件自己

2017-03-14 06:38 UTC, atian25 commented
+1

2017-03-14 07:01 UTC, ngot commented
https://github.com/xtemplate/xtemplate/issues/94

2017-03-14 07:21 UTC, atian25 commented
@popomore 看看有没有问题，没的话可以先发个 minor 了

2017-03-14 08:06 UTC, popomore commented on lib/xtpl.js
> +  encoding: 'utf-8',
这个不能通过 config.xtpl 配置？

2017-03-14 08:06 UTC, popomore commented on lib/view.js
> +    return this.app.xtpl.render(filename, locals, config);
这个需要用 yield 了吧

2017-03-14 08:06 UTC, popomore commented on lib/view.js
> +    return this.app.xtpl.render(filename, locals, config);
这个要用 yield 吧

2017-03-14 08:11 UTC, popomore commented
其他 +1

2017-03-14 08:35 UTC, ngot commented on lib/view.js
> +    return this.app.xtpl.render(filename, locals, config);
这样可以的。yield的话，这个方法得改成 generator。

2017-03-14 08:40 UTC, ngot commented on lib/xtpl.js
> +  encoding: 'utf-8',
我写的多余了。我删除了。

2017-03-14 08:40 UTC, ngot commented on lib/view.js
> +    return this.app.xtpl.render(filename, locals, config);
这个调整为generator了

2017-03-14 08:42 UTC, ngot commented
我合并，发个minor

2017-03-14 08:46 UTC, merged

2017-03-14 08:50 UTC, ngot commented
+ egg-view-xtpl@1.1.0